FROM nginx:1.12.0-alpine

ARG DOCKER_DIR=docker

COPY ${DOCKER_DIR}/.htpasswd	/etc/nginx/.htpasswd
COPY ${DOCKER_DIR}/nginx.conf /etc/nginx/nginx.conf 
COPY ${DOCKER_DIR}/certificate.crt /etc/nginx/ssl/certificate.crt
COPY ${DOCKER_DIR}/privatekey.key  /etc/nginx/ssl/privatekey.key
